#!/bin/bash

set -eo pipefail

source ./lib/target_prep

echo "-----> Install mini_portile"
gem install mini_portile --no-ri --no-rdoc

echo "-----> Run builder"
cd $TMP_DIR

ruby $LIB_DIR/mri_builder.rb \
  $1 \
  $2 \
  $OUTPUT

