Vagrant.configure("2") do |config|
  config.vm.box = 'https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vmwarefusion.box'
  config.vm.provision "shell", inline: "sudo apt-get -y install docker.io"
  config.vm.provision "shell", inline: "sudo ln -s `which docker.io` /usr/bin/docker"
end

